# Code Generated by Sidekick is for learning and experimentation purposes only.
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Page configuration
st.set_page_config(page_title="Data Science Explorer", page_icon="📊", layout="wide")

# Title and description
st.title("📊 Simple Data Science Project")
st.markdown("Upload your CSV file or use sample data to explore, visualize, and build models!")

# Sidebar for navigation
st.sidebar.header("Navigation")
page = st.sidebar.radio("Choose a page:", ["Data Upload", "Data Exploration", "Visualization", "Machine Learning"])

# Initialize session state for data
if 'df' not in st.session_state:
    st.session_state.df = None

# Page 1: Data Upload
if page == "Data Upload":
    st.header("📁 Upload Your Data")

    # Option to use sample data
    use_sample = st.checkbox("Use sample Iris dataset")

    if use_sample:
        from sklearn.datasets import load_iris

        iris = load_iris()
        df = pd.DataFrame(iris.data, columns=iris.feature_names)
        df['target'] = iris.target
        df['species'] = df['target'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})
        st.session_state.df = df
        st.success("✅ Sample Iris dataset loaded!")
    else:
        uploaded_file = st.file_uploader("Choose a CSV file", type=['csv'])

        if uploaded_file is not None:
            df = pd.read_csv(uploaded_file)
            st.session_state.df = df
            st.success("✅ File uploaded successfully!")

    # Display data
    if st.session_state.df is not None:
        st.subheader("Preview of Data")
        st.dataframe(st.session_state.df.head(10))

        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Total Rows", st.session_state.df.shape[0])
        with col2:
            st.metric("Total Columns", st.session_state.df.shape[1])
        with col3:
            st.metric("Missing Values", st.session_state.df.isnull().sum().sum())

# Page 2: Data Exploration
elif page == "Data Exploration":
    st.header("🔍 Data Exploration")

    if st.session_state.df is None:
        st.warning("⚠️ Please upload data first in the 'Data Upload' page!")
    else:
        df = st.session_state.df

        # Basic statistics
        st.subheader("Statistical Summary")
        st.dataframe(df.describe())

        # Data types
        st.subheader("Data Types")
        st.dataframe(pd.DataFrame(df.dtypes, columns=['Data Type']))

        # Missing values analysis
        st.subheader("Missing Values Analysis")
        missing_data = pd.DataFrame({
            'Column': df.columns,
            'Missing Count': df.isnull().sum(),
            'Missing Percentage': (df.isnull().sum() / len(df) * 100).round(2)
        })
        st.dataframe(missing_data)

        # Correlation matrix for numerical columns
        numerical_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        if len(numerical_cols) > 1:
            st.subheader("Correlation Matrix")
            corr_matrix = df[numerical_cols].corr()
            fig = px.imshow(corr_matrix,
                            text_auto=True,
                            aspect="auto",
                            color_continuous_scale='RdBu_r',
                            title="Correlation Heatmap")
            st.plotly_chart(fig, use_container_width=True)

# Page 3: Visualization
elif page == "Visualization":
    st.header("📈 Data Visualization")

    if st.session_state.df is None:
        st.warning("⚠️ Please upload data first in the 'Data Upload' page!")
    else:
        df = st.session_state.df

        # Select plot type
        plot_type = st.selectbox("Select Plot Type",
                                 ["Scatter Plot", "Line Chart", "Bar Chart", "Histogram", "Box Plot"])

        numerical_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

        if plot_type == "Scatter Plot":
            col1, col2 = st.columns(2)
            with col1:
                x_axis = st.selectbox("X-axis", numerical_cols)
            with col2:
                y_axis = st.selectbox("Y-axis", numerical_cols)

            color_by = st.selectbox("Color by (optional)", [None] + categorical_cols)

            fig = px.scatter(df, x=x_axis, y=y_axis, color=color_by,
                             title=f"{y_axis} vs {x_axis}")
            st.plotly_chart(fig, use_container_width=True)

        elif plot_type == "Histogram":
            column = st.selectbox("Select Column", numerical_cols)
            bins = st.slider("Number of bins", 5, 50, 20)

            fig = px.histogram(df, x=column, nbins=bins, title=f"Distribution of {column}")
            st.plotly_chart(fig, use_container_width=True)

        elif plot_type == "Box Plot":
            column = st.selectbox("Select Column", numerical_cols)
            group_by = st.selectbox("Group by (optional)", [None] + categorical_cols)

            fig = px.box(df, y=column, x=group_by, title=f"Box Plot of {column}")
            st.plotly_chart(fig, use_container_width=True)

# Page 4: Machine Learning
elif page == "Machine Learning":
    st.header("🤖 Machine Learning Model")

    if st.session_state.df is None:
        st.warning("⚠️ Please upload data first in the 'Data Upload' page!")
    else:
        df = st.session_state.df

        st.subheader("Build a Classification Model")

        # Select target column
        target_col = st.selectbox("Select Target Column", df.columns.tolist())

        # Select feature columns
        feature_cols = st.multiselect("Select Feature Columns",
                                      [col for col in df.columns if col != target_col])

        if len(feature_cols) > 0:
            # Prepare data
            X = df[feature_cols].select_dtypes(include=[np.number])
            y = df[target_col]

            # Train-test split
            test_size = st.slider("Test Set Size (%)", 10, 50, 20) / 100

            if st.button("Train Model"):
                with st.spinner("Training model..."):
                    X_train, X_test, y_train, y_test = train_test_split(
                        X, y, test_size=test_size, random_state=42
                    )

                    # Train Random Forest
                    model = RandomForestClassifier(n_estimators=100, random_state=42)
                    model.fit(X_train, y_train)

                    # Predictions
                    y_pred = model.predict(X_test)

                    # Results
                    st.success("✅ Model trained successfully!")

                    col1, col2 = st.columns(2)
                    with col1:
                        st.metric("Training Accuracy", f"{model.score(X_train, y_train):.2%}")
                    with col2:
                        st.metric("Test Accuracy", f"{accuracy_score(y_test, y_pred):.2%}")

                    # Feature importance
                    st.subheader("Feature Importance")
                    importance_df = pd.DataFrame({
                        'Feature': feature_cols,
                        'Importance': model.feature_importances_
                    }).sort_values('Importance', ascending=False)

                    fig = px.bar(importance_df, x='Importance', y='Feature',
                                 orientation='h', title="Feature Importance")
                    st.plotly_chart(fig, use_container_width=True)

                    # Classification report
                    st.subheader("Classification Report")
                    st.text(classification_report(y_test, y_pred))

# Footer
st.sidebar.markdown("---")
st.sidebar.info("Built with Streamlit 🎈")
